# Generated by Django 4.1.6 on 2023-02-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stat_cdnnow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat_settings',
            old_name='cliend_id',
            new_name='client_id',
        ),
    ]
