# Generated by Django 4.1.6 on 2023-02-16 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stat_cdnnow', '0002_rename_cliend_id_stat_settings_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='portals_stat',
            name='origin',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portals_stat',
            name='project',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
