# Generated by Django 4.1.6 on 2023-02-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stat_cdnnow', '0003_portals_stat_origin_portals_stat_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='portals_stat',
            name='old_project',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
